import type { Language } from "@/types";

export const copy: Record<Language, Record<string, string>> = {
  "zh-Hant": {
    "app.legacy": "原始聚合器", "app.open": "Open Renaiss", "app.source": "社群情報", "app.wiki": "前往新手 Wiki", "app.agent": "詢問 Renaiss Agent",
    "nav.overview": "總覽", "nav.events": "活動", "nav.official": "官方動態", "nav.feed": "社群動態", "nav.future": "未來規劃", "nav.sbt": "SBT", "nav.profile": "Profile", "nav.guide": "新手教學", "nav.records": "獎勵與紀錄", "nav.media": "新聞與媒體", "nav.knowledge": "知識與工具",
    "status.loading": "正在讀取 Renaiss 的即時情報", "status.live": "即時資料", "status.error": "無法讀取即時資料", "status.cards": "筆資訊", "status.translating": "翻譯處理中",
    "overview.lead": "將可驗證的官方活動、社群訊號、限時 SBT 與完整教學放在同一個入口。", "overview.events": "查看活動", "overview.feed": "看社群動態", "overview.source": "資料來源", "overview.happening": "正在發生", "overview.allEvents": "全部活動", "overview.limitedSbt": "限時 SBT 活動", "overview.allSbt": "完整 SBT 清單", "overview.limitedEmpty": "目前沒有具明確截止日、仍在有效期內的官方限時 SBT 活動。常駐任務請到新手教學查看。", "overview.signals": "值得留意的訊號", "overview.allSignals": "全部消息", "overview.start": "從這裡開始",
    "overview.route.official": "官方動態", "overview.route.officialSub": "官方公告與產品更新，不混入活動", "overview.route.feed": "社群動態", "overview.route.feedSub": "只看社群貼文與標記 Renaiss 的討論", "overview.route.events": "活動", "overview.route.eventsSub": "只看 Renaiss 官方活動狀態", "overview.route.future": "未來規劃", "overview.route.futureSub": "追蹤已標記的 Alpha 與後續更新", "overview.route.sbt": "SBT", "overview.route.sbtSub": "查看限時活動、文章與任務入口", "overview.route.records": "獎勵與紀錄", "overview.route.recordsSub": "只顯示可驗證的結果與排行", "overview.route.guide": "新手教學", "overview.route.guideSub": "完整保留原本的教學章節與工具",
    "official.title": "官方動態", "official.lead": "官方公告與產品更新會集中在這裡；已成立的活動請到活動頁查看。", "feed.title": "社群動態", "feed.lead": "只顯示社群貼文與標記 Renaiss 的討論，官方帳號內容不會混入。", "events.title": "活動", "events.lead": "只顯示 Renaiss 官方活動牆中的近期、已公告與過去活動；第三方卡牌通路活動不會混入。", "future.title": "未來規劃", "future.lead": "保留舊版 Alpha 分類中的已標記更新，集中查看後續計畫與需提前準備的事項。", "sbt.title": "SBT", "sbt.lead": "查看具明確條件與時間窗的官方 SBT 活動，以及相關文章。", "guide.title": "新手教學", "guide.lead": "完整保留獨立教學內容；一次閱讀一個章節，從左側切換。", "media.title": "新聞與媒體", "media.lead": "官方公告、收藏與 TCG 市場情報都能回到原始貼文或來源。", "knowledge.title": "知識與工具", "knowledge.lead": "保留原本已存在的工具與入口，各自負責最適合的工作。", "records.title": "獎勵、得獎者與排行榜", "records.lead": "只呈現可驗證的紀錄，不用推測或虛構名次。",
    "filter.all": "全部", "filter.official": "官方", "filter.community": "社群", "filter.tagged": "標記 Renaiss", "filter.active": "近期官方", "filter.upcoming": "已公告", "filter.past": "過去活動", "filter.market": "市場情報", "action.refresh": "重新整理", "action.original": "查看原文", "action.hub": "閱讀文章", "action.back": "返回 SBT", "action.guide": "完整 SBT 新手教學", "search.placeholder": "搜尋目前資料",
    "card.official": "官方", "card.community": "社群", "card.active": "進行中", "card.upcoming": "已公告", "card.past": "已結束", "card.reference": "參考", "card.defaultCover": "Renaiss Community 預設封面",
    "sbt.about": "SBT 是什麼？", "sbt.aboutBody": "Soulbound Token 是 Renaiss 參與與貢獻的鏈上紀錄。先理解它，再依任務條件行動。", "sbt.principle": "取得原則", "sbt.principleBody": "限時 SBT 只顯示有官方來源與明確有效期間的資料；常駐任務保留在完整新手教學。", "sbt.wikiLink": "想了解 SBT 是什麼？查看完整新手 Wiki", "sbt.analysis": "貼文分析", "sbt.acquisition": "限時活動與取得資訊", "sbt.acquisitionLead": "只列出來源中可辨識名稱、取得條件、起迄日與官方原文的活動。", "sbt.article": "SBT 相關文章", "sbt.articleLead": "點選文章卡片即可在 Hub 內閱讀摘要，再對照原文。", "sbt.articleEmpty": "目前沒有可在 Hub 內閱讀的 SBT 文章。", "sbt.currentCatalog": "目前可取得的 SBT", "sbt.currentCatalogLead": "依 Renaiss SBT catalog 顯示已標為 Available 的常駐取得路徑；限時項目會另外列出。", "sbt.availableStatus": "可取得", "sbt.difficulty": "難度", "sbt.available": "貼文自動整理", "sbt.availableLead": "從貼文已結構化的 SBT 名稱與取得條件彙整；未填欄位的貼文不會被推測補入。", "sbt.availableEmpty": "近期貼文尚未有可驗證的結構化 SBT 取得條件。", "sbt.legacyAvailable": "常駐可完成任務", "sbt.legacyAvailableLead": "這些是原本新手教學中的常駐任務，不會被誤列為限時活動。", "sbt.none": "目前沒有符合條件的官方限時 SBT 活動。",
    "records.winners": "得獎者與禮品", "records.packRank": "抽卡排行榜", "records.packRankSource": "Open Monitor · 抽卡排行 Top 200", "records.packRankLead": "排行榜資料由 Renaiss 後端直接接入 Open Monitor API，不是把使用者導向外部網站。", "records.packRankMeta": "資料來源為公開統計 · Renaiss 後端快取 5 分鐘", "records.packRankAction": "查看抽卡排行榜", "records.packRankTotal": "總抽卡", "records.packRankPlayers": "玩家數", "records.packRankUpdated": "資料快照", "records.packRankPulls": "抽卡", "records.packRankLoading": "正在載入排行榜資料", "records.packRankError": "排行榜資料暫時無法取得", "records.packRankEmpty": "目前沒有可顯示的排行榜資料", "records.packRankNoPackBreakdown": "沒有卡池分布資料", "records.packRankSnapshotUnknown": "未知", "records.packRankSourceLink": "查看來源說明", "records.winnerMissing": "尚未接入可驗證的官方得獎名單。",
    "empty.unavailable": "目前沒有符合來源規則的資料。", "empty.translating": "翻譯仍在處理中，完成後會自動重新讀取。", "guide.source": "資料來源", "guide.sourceLead": "內容整理來源：老豆子 @genekmkz 與其 Notion。", "guide.x": "X：老豆子 @genekmkz", "guide.notion": "Notion：Renaiss 指南",
  },
  "zh-Hans": {
    "app.legacy": "原始聚合器", "app.open": "Open Renaiss", "app.source": "社群情报", "app.wiki": "前往新手 Wiki", "app.agent": "询问 Renaiss Agent",
    "nav.overview": "总览", "nav.events": "活动", "nav.official": "官方动态", "nav.feed": "社群动态", "nav.future": "未来规划", "nav.sbt": "SBT", "nav.profile": "Profile", "nav.guide": "新手教学", "nav.records": "奖励与纪录", "nav.media": "新闻与媒体", "nav.knowledge": "知识与工具",
    "status.loading": "正在读取 Renaiss 的即时情报", "status.live": "即时资料", "status.error": "无法读取即时资料", "status.cards": "条资讯", "status.translating": "翻译处理中",
    "overview.lead": "将可验证的官方活动、社群讯号、限时 SBT 与完整教学放在同一个入口。", "overview.events": "查看活动", "overview.feed": "看社群动态", "overview.source": "资料来源", "overview.happening": "正在发生", "overview.allEvents": "全部活动", "overview.limitedSbt": "限时 SBT 活动", "overview.allSbt": "完整 SBT 清单", "overview.limitedEmpty": "目前没有具明确截止日、仍在有效期内的官方限时 SBT 活动。常驻任务请到新手教学查看。", "overview.signals": "值得留意的讯号", "overview.allSignals": "全部消息", "overview.start": "从这里开始",
    "overview.route.official": "官方动态", "overview.route.officialSub": "官方公告与产品更新，不混入活动", "overview.route.feed": "社群动态", "overview.route.feedSub": "只看社群贴文与标记 Renaiss 的讨论", "overview.route.events": "活动", "overview.route.eventsSub": "只看 Renaiss 官方活动状态", "overview.route.future": "未来规划", "overview.route.futureSub": "追踪已标记的 Alpha 与后续更新", "overview.route.sbt": "SBT", "overview.route.sbtSub": "查看限时活动、文章与任务入口", "overview.route.records": "奖励与纪录", "overview.route.recordsSub": "只显示可验证的结果与排行", "overview.route.guide": "新手教学", "overview.route.guideSub": "完整保留原本的教学章节与工具",
    "official.title": "官方动态", "official.lead": "官方公告与产品更新会集中在这里；已成立的活动请到活动页查看。", "feed.title": "社群动态", "feed.lead": "只显示社群贴文与标记 Renaiss 的讨论，官方帐号内容不会混入。", "events.title": "活动", "events.lead": "只显示 Renaiss 官方活动墙中的近期、已公告与过去活动；第三方卡牌通路活动不会混入。", "future.title": "未来规划", "future.lead": "保留旧版 Alpha 分类中已标记的更新，集中查看后续计划与需提前准备的事项。", "sbt.title": "SBT", "sbt.lead": "查看具明确条件与时间窗的官方 SBT 活动，以及相关文章。", "guide.title": "新手教学", "guide.lead": "完整保留独立教学内容；一次阅读一个章节，从左侧切换。", "media.title": "新闻与媒体", "media.lead": "官方公告、收藏与 TCG 市场情报都能回到原始贴文或来源。", "knowledge.title": "知识与工具", "knowledge.lead": "保留原本已存在的工具与入口，各自负责最适合的工作。", "records.title": "奖励、得奖者与排行榜", "records.lead": "只呈现可验证的纪录，不用推测或虚构名次。",
    "filter.all": "全部", "filter.official": "官方", "filter.community": "社群", "filter.tagged": "标记 Renaiss", "filter.active": "近期官方", "filter.upcoming": "已公告", "filter.past": "过去活动", "filter.market": "市场情报", "action.refresh": "重新整理", "action.original": "查看原文", "action.hub": "阅读文章", "action.back": "返回 SBT", "action.guide": "完整 SBT 新手教学", "search.placeholder": "搜寻目前资料",
    "card.official": "官方", "card.community": "社群", "card.active": "进行中", "card.upcoming": "已公告", "card.past": "已结束", "card.reference": "参考", "card.defaultCover": "Renaiss Community 默认封面",
    "sbt.about": "SBT 是什么？", "sbt.aboutBody": "Soulbound Token 是 Renaiss 参与与贡献的链上记录。先理解它，再依任务条件行动。", "sbt.principle": "获取原则", "sbt.principleBody": "限时 SBT 只显示有官方来源与明确有效期间的资料；常驻任务保留在完整新手教学。", "sbt.wikiLink": "想了解 SBT 是什么？查看完整新手 Wiki", "sbt.analysis": "贴文分析", "sbt.acquisition": "限时活动与获取资讯", "sbt.acquisitionLead": "只列出来源中可识别名称、获取条件、起迄日与官方原文的活动。", "sbt.article": "SBT 相关文章", "sbt.articleLead": "点选文章卡片即可在 Hub 内阅读摘要，再对照原文。", "sbt.articleEmpty": "目前没有可在 Hub 内阅读的 SBT 文章。", "sbt.currentCatalog": "目前可取得的 SBT", "sbt.currentCatalogLead": "依 Renaiss SBT catalog 显示已标为 Available 的常驻获取路径；限时项目会另行列出。", "sbt.availableStatus": "可获取", "sbt.difficulty": "难度", "sbt.available": "贴文自动整理", "sbt.availableLead": "从贴文已结构化的 SBT 名称与获取条件汇整；未填写栏位的贴文不会被推测补入。", "sbt.availableEmpty": "近期贴文尚未有可验证的结构化 SBT 获取条件。", "sbt.legacyAvailable": "常驻可完成任务", "sbt.legacyAvailableLead": "这些是原本新手教学中的常驻任务，不会被误列为限时活动。", "sbt.none": "目前没有符合条件的官方限时 SBT 活动。",
    "records.winners": "得奖者与礼品", "records.packRank": "抽卡排行榜", "records.packRankSource": "Open Monitor · 抽卡排行 Top 200", "records.packRankLead": "排行榜资料由 Renaiss 后端直接接入 Open Monitor API，不是把使用者导向外部网站。", "records.packRankMeta": "资料来源为公开统计 · Renaiss 后端快取 5 分钟", "records.packRankAction": "查看抽卡排行榜", "records.packRankTotal": "总抽卡", "records.packRankPlayers": "玩家数", "records.packRankUpdated": "资料快照", "records.packRankPulls": "抽卡", "records.packRankLoading": "正在载入排行榜资料", "records.packRankError": "排行榜资料暂时无法取得", "records.packRankEmpty": "目前没有可显示的排行榜资料", "records.packRankNoPackBreakdown": "没有卡池分布资料", "records.packRankSnapshotUnknown": "未知", "records.packRankSourceLink": "查看来源说明", "records.winnerMissing": "尚未接入可验证的官方得奖名单。",
    "empty.unavailable": "目前没有符合来源规则的资料。", "empty.translating": "翻译仍在处理中，完成后会自动重新读取。", "guide.source": "资料来源", "guide.sourceLead": "内容整理来源：老豆子 @genekmkz 与其 Notion。", "guide.x": "X：老豆子 @genekmkz", "guide.notion": "Notion：Renaiss 指南",
  },
  en: {
    "app.legacy": "Legacy aggregator", "app.open": "Open Renaiss", "app.source": "Community intelligence", "app.wiki": "Open beginner Wiki", "app.agent": "Ask Renaiss Agent",
    "nav.overview": "Overview", "nav.events": "Events", "nav.official": "Official updates", "nav.feed": "Community feed", "nav.future": "Future plans", "nav.sbt": "SBT", "nav.profile": "Profile", "nav.guide": "Beginner guide", "nav.records": "Rewards and records", "nav.media": "News and media", "nav.knowledge": "Knowledge and tools",
    "status.loading": "Loading live Renaiss intelligence", "status.live": "Live data", "status.error": "Unable to load live data", "status.cards": "items", "status.translating": "Translation in progress",
    "overview.lead": "A single entry point for verified official events, community signals, limited SBTs, and the complete guide.", "overview.events": "View events", "overview.feed": "Community feed", "overview.source": "Source", "overview.happening": "Happening now", "overview.allEvents": "All events", "overview.limitedSbt": "Limited SBT campaigns", "overview.allSbt": "Full SBT list", "overview.limitedEmpty": "There are no official limited SBT campaigns with a clear active deadline. See the beginner guide for evergreen tasks.", "overview.signals": "Signals to watch", "overview.allSignals": "All updates", "overview.start": "Start here",
    "overview.route.official": "Official updates", "overview.route.officialSub": "Official announcements and product updates, separate from events", "overview.route.feed": "Community feed", "overview.route.feedSub": "Community posts and Renaiss-tagged discussion only", "overview.route.events": "Events", "overview.route.eventsSub": "See official Renaiss event status only", "overview.route.future": "Future plans", "overview.route.futureSub": "Track Alpha-tagged plans and follow-up updates", "overview.route.sbt": "SBT", "overview.route.sbtSub": "Limited campaigns, articles, and task entry points", "overview.route.records": "Rewards and records", "overview.route.recordsSub": "Verified results and rankings only", "overview.route.guide": "Beginner guide", "overview.route.guideSub": "All original chapters and tools",
    "official.title": "Official updates", "official.lead": "Official announcements and product updates are collected here. Established campaigns stay on the Events page.", "feed.title": "Community feed", "feed.lead": "Community posts and Renaiss-tagged discussion only. Official-account content is kept separate.", "events.title": "Events", "events.lead": "Only official Renaiss event-wall records appear here. Third-party card-channel campaigns are excluded.", "future.title": "Future plans", "future.lead": "The Alpha-tagged updates from the original site, organized for following upcoming plans and preparation.", "sbt.title": "SBT", "sbt.lead": "Review official SBT campaigns with clear conditions and time windows, plus related articles.", "guide.title": "Beginner guide", "guide.lead": "The complete independent guide is retained. Read one chapter at a time from the left navigation.", "media.title": "News and media", "media.lead": "Official announcements, collectible updates, and TCG market signals always link to their original source.", "knowledge.title": "Knowledge and tools", "knowledge.lead": "Existing tools and entry points stay separate so each can do the job it is designed for.", "records.title": "Rewards, winners, and rankings", "records.lead": "Only verifiable records appear here. No inferred or fabricated rankings.",
    "filter.all": "All", "filter.official": "Official", "filter.community": "Community", "filter.tagged": "Tagged Renaiss", "filter.active": "Recent official", "filter.upcoming": "Announced", "filter.past": "Past", "filter.market": "Market", "action.refresh": "Refresh", "action.original": "Open source", "action.hub": "Read article", "action.back": "Back to SBT", "action.guide": "Complete SBT beginner guide", "search.placeholder": "Search current data",
    "card.official": "Official", "card.community": "Community", "card.active": "Active", "card.upcoming": "Announced", "card.past": "Ended", "card.reference": "Reference", "card.defaultCover": "Renaiss Community default cover",
    "sbt.about": "What is an SBT?", "sbt.aboutBody": "Soulbound Tokens are on-chain records of participation and contribution in Renaiss. Understand the context before acting on a task.", "sbt.principle": "Earning principle", "sbt.principleBody": "Limited SBTs require an official source and an explicit active period. Evergreen tasks remain in the full beginner guide.", "sbt.wikiLink": "Need an SBT introduction? Open the complete beginner Wiki", "sbt.analysis": "Post analysis", "sbt.acquisition": "Limited campaigns and earning details", "sbt.acquisitionLead": "Only items with a name, requirement, dates, and official source are listed.", "sbt.article": "SBT articles", "sbt.articleLead": "Select an article card to read its summary in the Hub, then compare the source.", "sbt.articleEmpty": "No SBT articles are currently available for in-Hub reading.", "sbt.currentCatalog": "Available SBT paths", "sbt.currentCatalogLead": "These are evergreen paths marked Available in the maintained Renaiss SBT catalog. Limited opportunities are listed separately.", "sbt.availableStatus": "Available", "sbt.difficulty": "Difficulty", "sbt.available": "Post analysis", "sbt.availableLead": "Only posts with structured SBT names and earning conditions are summarized here; missing fields are not guessed.", "sbt.availableEmpty": "Recent posts do not yet provide a verifiable structured SBT earning condition.", "sbt.legacyAvailable": "Evergreen tasks", "sbt.legacyAvailableLead": "These are original beginner-guide tasks and are not represented as limited campaigns.", "sbt.none": "There are no qualifying official limited SBT campaigns right now.",
    "records.winners": "Winners and gifts", "records.packRank": "Pack-opening leaderboard", "records.packRankSource": "Open Monitor · Top 200 pack openers", "records.packRankLead": "The Renaiss backend reads the Open Monitor API directly, so this is data inside the Hub rather than a link-out page.", "records.packRankMeta": "Public statistics · Cached by the Renaiss backend for 5 minutes", "records.packRankAction": "Open pack leaderboard", "records.packRankTotal": "Total pulls", "records.packRankPlayers": "Players", "records.packRankUpdated": "Snapshot", "records.packRankPulls": "pulls", "records.packRankLoading": "Loading leaderboard data", "records.packRankError": "Leaderboard data is temporarily unavailable", "records.packRankEmpty": "No leaderboard data is available right now", "records.packRankNoPackBreakdown": "No pack breakdown", "records.packRankSnapshotUnknown": "Unknown", "records.packRankSourceLink": "View source details", "records.winnerMissing": "No verifiable official winner list has been connected yet.",
    "empty.unavailable": "No records match the current source rules.", "empty.translating": "Translation is still processing and will be loaded again when ready.", "guide.source": "Sources", "guide.sourceLead": "Guide materials are credited to @genekmkz and the associated Notion guide.", "guide.x": "X: @genekmkz", "guide.notion": "Notion: Renaiss Guide",
  },
  ko: {
    "app.legacy": "기존 애그리게이터", "app.open": "Open Renaiss", "app.source": "커뮤니티 인텔리전스", "app.wiki": "초보자 Wiki 열기", "app.agent": "Renaiss Agent에게 묻기",
    "nav.overview": "개요", "nav.events": "이벤트", "nav.official": "공식 업데이트", "nav.feed": "커뮤니티 피드", "nav.future": "미래 계획", "nav.sbt": "SBT", "nav.profile": "Profile", "nav.guide": "초보자 가이드", "nav.records": "보상 및 기록", "nav.media": "뉴스 및 미디어", "nav.knowledge": "지식 및 도구",
    "status.loading": "실시간 Renaiss 정보를 불러오는 중", "status.live": "실시간 데이터", "status.error": "실시간 데이터를 불러올 수 없습니다", "status.cards": "개 항목", "status.translating": "번역 처리 중",
    "overview.lead": "검증된 공식 이벤트, 커뮤니티 신호, 기간 한정 SBT, 전체 가이드를 하나의 진입점에 모았습니다.", "overview.events": "이벤트 보기", "overview.feed": "커뮤니티 피드", "overview.source": "출처", "overview.happening": "지금 진행 중", "overview.allEvents": "모든 이벤트", "overview.limitedSbt": "기간 한정 SBT 캠페인", "overview.allSbt": "전체 SBT 목록", "overview.limitedEmpty": "명확한 마감일이 있는 공식 기간 한정 SBT 캠페인이 없습니다. 상시 과제는 초보자 가이드에서 확인하세요.", "overview.signals": "주목할 신호", "overview.allSignals": "모든 업데이트", "overview.start": "여기서 시작",
    "overview.route.official": "공식 업데이트", "overview.route.officialSub": "이벤트와 분리된 공식 공지 및 제품 업데이트", "overview.route.feed": "커뮤니티 피드", "overview.route.feedSub": "커뮤니티 게시물과 Renaiss 태그 토론만 보기", "overview.route.events": "이벤트", "overview.route.eventsSub": "공식 Renaiss 이벤트 상태만 보기", "overview.route.future": "미래 계획", "overview.route.futureSub": "Alpha 태그 계획과 후속 업데이트 추적", "overview.route.sbt": "SBT", "overview.route.sbtSub": "기간 한정 캠페인, 글, 과제 진입점", "overview.route.records": "보상 및 기록", "overview.route.recordsSub": "검증된 결과와 순위만 보기", "overview.route.guide": "초보자 가이드", "overview.route.guideSub": "원래의 모든 장과 도구를 보존",
    "official.title": "공식 업데이트", "official.lead": "공식 공지와 제품 업데이트를 모았습니다. 확정된 캠페인은 이벤트 페이지에서 확인하세요.", "feed.title": "커뮤니티 피드", "feed.lead": "커뮤니티 게시물과 Renaiss 태그 토론만 표시합니다. 공식 계정 내용은 별도로 분리합니다.", "events.title": "이벤트", "events.lead": "공식 Renaiss 이벤트 월의 최근, 공지됨, 과거 이벤트만 표시합니다. 외부 카드 채널 캠페인은 제외됩니다.", "future.title": "미래 계획", "future.lead": "기존 사이트 Alpha 분류의 업데이트를 모아 향후 계획과 사전 준비 사항을 확인합니다.", "sbt.title": "SBT", "sbt.lead": "명확한 조건과 기간이 있는 공식 SBT 캠페인과 관련 글을 확인하세요.", "guide.title": "초보자 가이드", "guide.lead": "독립된 전체 가이드를 보존합니다. 왼쪽에서 한 번에 한 장씩 읽으세요.", "media.title": "뉴스 및 미디어", "media.lead": "공식 공지, 컬렉터블 및 TCG 시장 정보는 원문으로 돌아갈 수 있습니다.", "knowledge.title": "지식 및 도구", "knowledge.lead": "기존 도구와 진입점은 각자 가장 적합한 역할을 할 수 있도록 분리합니다.", "records.title": "보상, 수상자 및 순위", "records.lead": "검증 가능한 기록만 표시합니다. 추정하거나 꾸며낸 순위는 표시하지 않습니다.",
    "filter.all": "전체", "filter.official": "공식", "filter.community": "커뮤니티", "filter.tagged": "Renaiss 태그", "filter.active": "최근 공식", "filter.upcoming": "공지됨", "filter.past": "과거", "filter.market": "시장", "action.refresh": "새로고침", "action.original": "원문 보기", "action.hub": "글 읽기", "action.back": "SBT로 돌아가기", "action.guide": "전체 SBT 초보자 가이드", "search.placeholder": "현재 데이터 검색",
    "card.official": "공식", "card.community": "커뮤니티", "card.active": "진행 중", "card.upcoming": "공지됨", "card.past": "종료됨", "card.reference": "참고", "card.defaultCover": "Renaiss Community 기본 표지",
    "sbt.about": "SBT란?", "sbt.aboutBody": "Soulbound Token은 Renaiss에서의 참여와 기여를 보여주는 온체인 기록입니다. 과제 전에 맥락을 이해하세요.", "sbt.principle": "획득 원칙", "sbt.principleBody": "기간 한정 SBT는 공식 출처와 명확한 유효 기간이 있어야 합니다. 상시 과제는 전체 초보자 가이드에 남깁니다.", "sbt.wikiLink": "SBT 소개가 필요하신가요? 전체 초보자 Wiki 열기", "sbt.analysis": "게시물 분석", "sbt.acquisition": "기간 한정 캠페인과 획득 정보", "sbt.acquisitionLead": "이름, 조건, 일정 및 공식 출처가 확인되는 항목만 표시합니다.", "sbt.article": "SBT 관련 글", "sbt.articleLead": "글 카드를 선택하면 Hub에서 요약을 읽고 원문과 대조할 수 있습니다.", "sbt.articleEmpty": "현재 Hub에서 읽을 수 있는 SBT 글이 없습니다.", "sbt.currentCatalog": "현재 획득 가능한 SBT", "sbt.currentCatalogLead": "관리 중인 Renaiss SBT catalog에서 Available로 표시된 상시 획득 경로입니다. 기간 한정 기회는 별도로 표시됩니다.", "sbt.availableStatus": "획득 가능", "sbt.difficulty": "난이도", "sbt.available": "게시물 자동 정리", "sbt.availableLead": "구조화된 SBT 이름과 획득 조건이 있는 게시물만 정리하며, 누락된 필드는 추측으로 채우지 않습니다.", "sbt.availableEmpty": "최근 게시물에 검증 가능한 구조화 SBT 획득 조건이 없습니다.", "sbt.legacyAvailable": "상시 가능 과제", "sbt.legacyAvailableLead": "원래 초보자 가이드의 과제이며 기간 한정 캠페인으로 표시하지 않습니다.", "sbt.none": "현재 조건을 충족하는 공식 기간 한정 SBT 캠페인이 없습니다.",
    "records.winners": "수상자와 선물", "records.packRank": "팩 오픈 랭킹", "records.packRankSource": "Open Monitor · 팩 오픈 Top 200", "records.packRankLead": "Renaiss 백엔드가 Open Monitor API를 직접 읽습니다. 외부 사이트로 이동하는 링크가 아니라 Hub 안의 데이터입니다.", "records.packRankMeta": "공개 통계 · Renaiss 백엔드 5분 캐시", "records.packRankAction": "팩 오픈 랭킹 열기", "records.packRankTotal": "총 오픈", "records.packRankPlayers": "플레이어", "records.packRankUpdated": "스냅샷", "records.packRankPulls": "오픈", "records.packRankLoading": "랭킹 데이터를 불러오는 중", "records.packRankError": "랭킹 데이터를 잠시 불러올 수 없습니다", "records.packRankEmpty": "현재 표시할 랭킹 데이터가 없습니다", "records.packRankNoPackBreakdown": "팩 분포 없음", "records.packRankSnapshotUnknown": "알 수 없음", "records.packRankSourceLink": "출처 상세 보기", "records.winnerMissing": "검증 가능한 공식 수상자 명단이 아직 연결되지 않았습니다.",
    "empty.unavailable": "현재 출처 규칙에 맞는 기록이 없습니다.", "empty.translating": "번역이 아직 처리 중이며 준비되면 다시 불러옵니다.", "guide.source": "출처", "guide.sourceLead": "가이드 자료 출처: @genekmkz와 해당 Notion 가이드.", "guide.x": "X: @genekmkz", "guide.notion": "Notion: Renaiss Guide",
  },
};

export function text(lang: Language, key: string): string {
  return copy[lang][key] ?? copy["zh-Hant"][key] ?? key;
}
