import type { Language } from "@/types";

export const copy: Record<Language, Record<string, string>> = {
  "zh-Hant": {
    "card.pinned": "置頂",
    "app.legacy": "原始聚合器", "app.open": "Open Renaiss", "app.source": "社群情報", "app.wiki": "前往新手 Wiki", "app.agent": "詢問 Renaiss Agent", "auth.login": "登入編輯", "auth.logout": "登出", "auth.account": "Renaiss 帳號", "auth.checking": "確認登入",
    "nav.overview": "總覽", "nav.events": "活動", "nav.official": "官方動態", "nav.feed": "社群動態", "nav.future": "產品進度", "nav.sbt": "SBT", "nav.profile": "Profile", "nav.guide": "新手教學", "nav.records": "獎勵與紀錄", "nav.media": "新聞與媒體", "nav.knowledge": "知識與工具", "nav.manage": "內容管理",
    "status.loading": "正在讀取 Renaiss 的即時情報", "status.live": "即時資料", "status.error": "無法讀取即時資料", "status.cards": "筆資訊", "status.translating": "翻譯處理中",
    "overview.lead": "將可驗證的官方活動、社群訊號、限時 SBT 與完整教學放在同一個入口。", "overview.events": "查看活動", "overview.feed": "看社群動態", "overview.source": "資料來源", "overview.happening": "正在發生", "overview.allEvents": "全部活動", "overview.limitedSbt": "限時 SBT 活動", "overview.allSbt": "完整 SBT 清單", "overview.limitedEmpty": "目前沒有具明確截止日、仍在有效期內的官方限時 SBT 活動。常駐任務請到新手教學查看。", "overview.signals": "值得留意的訊號", "overview.allSignals": "全部消息", "overview.start": "從這裡開始",
    "overview.route.official": "官方動態", "overview.route.officialSub": "官方公告與產品更新，不混入活動", "overview.route.feed": "社群動態", "overview.route.feedSub": "只看社群貼文與標記 Renaiss 的討論", "overview.route.events": "活動", "overview.route.eventsSub": "只看 Renaiss 官方活動狀態", "overview.route.future": "產品進度", "overview.route.futureSub": "由 AI 依日期與原文整理規劃狀態", "overview.route.sbt": "SBT", "overview.route.sbtSub": "查看限時活動、文章與任務入口", "overview.route.records": "獎勵與紀錄", "overview.route.recordsSub": "只顯示可驗證的結果與排行", "overview.route.guide": "新手教學", "overview.route.guideSub": "完整保留原本的教學章節與工具",
    "official.title": "官方動態", "official.lead": "官方公告與產品更新會集中在這裡；已成立的活動請到活動頁查看。", "official.aiSummary": "AI 摘要", "official.summaryEyebrow": "AI WEEKLY BRIEF", "official.summaryTitle": "近七天官方摘要", "official.summaryClose": "關閉官方摘要", "official.summaryUnavailable": "近七天摘要尚未完成，請稍後重新整理。", "feed.title": "社群動態", "feed.lead": "只顯示社群貼文與標記 Renaiss 的討論，官方帳號內容不會混入。", "events.title": "活動", "events.lead": "集中 Renaiss 主帳號與地區社群帳號的活動；目前語言所對應的地區以金色標示，其他地區統一以藍色呈現。", "future.title": "產品進度", "future.lead": "依 @renaissxyz 主帳號原文與目前日期整理產品進度；其他帳號不會混入。", "future.pending": "主帳號既有資料正等待完成生命週期分類。", "sbt.title": "SBT 系統整理", "sbt.lead": "先確認近期與常駐的 SBT 取得方式，再閱讀相關文章與官方來源。", "guide.title": "新手教學", "guide.lead": "完整保留獨立教學內容；一次閱讀一個章節，從左側切換。", "media.title": "新聞與媒體", "media.lead": "官方公告、收藏與 TCG 市場情報都能回到原始貼文或來源。", "knowledge.title": "知識與工具", "knowledge.lead": "保留原本已存在的工具與入口，各自負責最適合的工作。", "records.title": "獎勵、得獎者與排行榜", "records.lead": "只呈現可驗證的紀錄，不用推測或虛構名次。",
    "filter.all": "全部", "filter.official": "官方", "filter.community": "社群", "filter.tagged": "標記 Renaiss", "filter.active": "進行中", "filter.upcoming": "已公告", "filter.past": "過去活動", "filter.market": "市場情報", "filter.planUpcoming": "即將推出", "filter.planActive": "進行中", "filter.planCompleted": "已完成", "filter.plan.upcoming": "即將推出", "filter.plan.in_progress": "進行中", "filter.plan.completed": "已完成", "filter.plan.cancelled": "已取消", "filter.plan.not_plan": "非產品規劃", "filter.plan.needs_review": "待確認", "action.refresh": "重新整理", "action.original": "查看原文", "action.hub": "閱讀文章", "action.back": "返回上一區", "action.guide": "完整 SBT 新手教學", "search.placeholder": "搜尋目前資料",
    "events.empty.active": "目前沒有進行中的官方活動。", "events.empty.upcoming": "目前沒有進行中或已公告的官方活動。", "events.empty.past": "目前沒有可顯示的過去活動。",
    "card.official": "官方", "card.regional": "地區社群", "card.community": "社群", "card.active": "進行中", "card.upcoming": "已公告", "card.past": "已結束", "card.reference": "參考", "card.defaultCover": "Renaiss Community 預設封面",
    "sbt.about": "SBT 是什麼？", "sbt.aboutBody": "Soulbound Token 是 Renaiss 參與與貢獻的鏈上紀錄。先理解它，再依任務條件行動。", "sbt.principle": "取得原則", "sbt.principleBody": "限時 SBT 只顯示有官方來源與明確有效期間的資料；常駐任務保留在完整新手教學。", "sbt.wikiLink": "前往完整新手 Wiki", "sbt.analysis": "貼文分析", "sbt.acquisition": "限時 SBT 取得", "sbt.acquisitionLead": "依近期貼文整理 SBT 名稱、取得方式與時效；有明確取得動作且沒有結束證據的項目標示為可取得。", "sbt.article": "SBT 相關文章", "sbt.articleLead": "點選文章卡片即可在 Hub 內閱讀摘要，再對照原文。", "sbt.articleEmpty": "目前沒有可在 Hub 內閱讀的 SBT 文章。", "sbt.currentCatalog": "常駐 SBT 任務", "sbt.currentCatalogLead": "無活動期限、可隨時完成的任務集中在完整新手 Wiki。", "sbt.availableStatus": "可取得", "sbt.difficulty": "難度", "sbt.available": "SBT 取得方式", "sbt.availableLead": "先看近期整理數量與狀態，再到下方逐筆核對；常駐任務則集中在完整新手 Wiki。", "sbt.methodRecent": "近期取得線索", "sbt.methodClaimable": "已確認可取得", "sbt.methodPending": "待確認", "sbt.methodExpired": "已過期", "sbt.availableEmpty": "近期貼文尚未整理出可核對的 SBT 取得方式。", "sbt.status.pending": "待確認", "sbt.status.claimable": "可取得", "sbt.status.expired": "已過期", "sbt.legacyAvailable": "常駐可完成任務", "sbt.legacyAvailableLead": "這些是原本新手教學中的常駐任務，不會被誤列為限時活動。", "sbt.none": "目前沒有符合條件的官方限時 SBT 活動。",
    "records.winners": "得獎者與禮品", "records.packRank": "抽卡排行榜", "records.packRankSource": "Open Monitor · 抽卡排行 Top 200", "records.packRankLead": "排行榜資料由 Renaiss 後端直接接入 Open Monitor API，不是把使用者導向外部網站。", "records.packRankMeta": "資料來源為公開統計 · Renaiss 後端快取 5 分鐘", "records.packRankAction": "查看抽卡排行榜", "records.packRankTotal": "總抽卡", "records.packRankPlayers": "玩家數", "records.packRankUpdated": "資料快照", "records.packRankPulls": "抽卡", "records.packRankLoading": "正在載入排行榜資料", "records.packRankError": "排行榜資料暫時無法取得", "records.packRankEmpty": "目前沒有可顯示的排行榜資料", "records.packRankNoPackBreakdown": "沒有卡池分布資料", "records.packRankSnapshotUnknown": "未知", "records.packRankSourceLink": "查看來源說明", "records.winnerMissing": "尚未接入可驗證的官方得獎名單。",
    "empty.unavailable": "目前沒有符合來源規則的資料。", "empty.translating": "翻譯仍在處理中，完成後會自動重新讀取。", "guide.source": "資料來源", "guide.sourceLead": "內容整理來源：老豆子 @genekmkz 與其 Notion。", "guide.x": "X：老豆子 @genekmkz", "guide.notion": "Notion：Renaiss 指南", "guide.articleLead": "AI 分類為 guides 的教學文章會永久收錄在這裡，不受近期時間窗影響。", "guide.articleCount": "篇教學文章", "guide.articleEmpty": "目前沒有被 AI 分類為 guides 的教學文章。",
    "community.mapTitle": "社群熱點地圖", "community.mapLead": "查看各地區近期互動聲量與熱門社群。", "community.mapTop": "目前第一名", "community.mapWaiting": "等待地區聲量資料", "community.mapOpenNew": "另開完整地圖", "community.mapClose": "關閉熱點地圖", "community.regionFilter": "依社群帳號地區篩選", "community.regionAll": "全部地區",
    "pagination.label": "內容分頁", "pagination.previous": "上一頁", "pagination.next": "下一頁", "pagination.page": "第",
    "article.published": "發布", "article.timeline": "內容日期", "article.facts": "活動資訊", "article.fact.schedule": "時間", "article.fact.location": "地點", "article.fact.participation": "參與方式", "article.fact.reward": "獎勵", "article.fact.audience": "適合對象", "article.highlights": "重點", "article.analysis": "完整整理", "article.details": "詳細內容", "article.sbt": "SBT 資訊", "article.plan": "產品進度判定", "article.sourceText": "原始內容", "article.partial": "完整原文暫時無法取得，以下僅保留可驗證的貼文預覽。", "article.tags": "文章分類",
  },
  "zh-Hans": {
    "card.pinned": "置顶",
    "app.legacy": "原始聚合器", "app.open": "Open Renaiss", "app.source": "社群情报", "app.wiki": "前往新手 Wiki", "app.agent": "询问 Renaiss Agent", "auth.login": "登录编辑", "auth.logout": "退出登录", "auth.account": "Renaiss 帐号", "auth.checking": "确认登录",
    "nav.overview": "总览", "nav.events": "活动", "nav.official": "官方动态", "nav.feed": "社群动态", "nav.future": "产品进度", "nav.sbt": "SBT", "nav.profile": "Profile", "nav.guide": "新手教学", "nav.records": "奖励与纪录", "nav.media": "新闻与媒体", "nav.knowledge": "知识与工具", "nav.manage": "内容管理",
    "status.loading": "正在读取 Renaiss 的即时情报", "status.live": "即时资料", "status.error": "无法读取即时资料", "status.cards": "条资讯", "status.translating": "翻译处理中",
    "overview.lead": "将可验证的官方活动、社群讯号、限时 SBT 与完整教学放在同一个入口。", "overview.events": "查看活动", "overview.feed": "看社群动态", "overview.source": "资料来源", "overview.happening": "正在发生", "overview.allEvents": "全部活动", "overview.limitedSbt": "限时 SBT 活动", "overview.allSbt": "完整 SBT 清单", "overview.limitedEmpty": "目前没有具明确截止日、仍在有效期内的官方限时 SBT 活动。常驻任务请到新手教学查看。", "overview.signals": "值得留意的讯号", "overview.allSignals": "全部消息", "overview.start": "从这里开始",
    "overview.route.official": "官方动态", "overview.route.officialSub": "官方公告与产品更新，不混入活动", "overview.route.feed": "社群动态", "overview.route.feedSub": "只看社群贴文与标记 Renaiss 的讨论", "overview.route.events": "活动", "overview.route.eventsSub": "只看 Renaiss 官方活动状态", "overview.route.future": "产品进度", "overview.route.futureSub": "由 AI 依日期与原文整理规划状态", "overview.route.sbt": "SBT", "overview.route.sbtSub": "查看限时活动、文章与任务入口", "overview.route.records": "奖励与纪录", "overview.route.recordsSub": "只显示可验证的结果与排行", "overview.route.guide": "新手教学", "overview.route.guideSub": "完整保留原本的教学章节与工具",
    "official.title": "官方动态", "official.lead": "官方公告与产品更新会集中在这里；已成立的活动请到活动页查看。", "official.aiSummary": "AI 摘要", "official.summaryEyebrow": "AI WEEKLY BRIEF", "official.summaryTitle": "近七天官方摘要", "official.summaryClose": "关闭官方摘要", "official.summaryUnavailable": "近七天摘要尚未完成，请稍后刷新。", "feed.title": "社群动态", "feed.lead": "只显示社群贴文与标记 Renaiss 的讨论，官方帐号内容不会混入。", "events.title": "活动", "events.lead": "集中 Renaiss 主帐号与地区社群帐号的活动；当前语言所对应的地区以金色标示，其他地区统一以蓝色呈现。", "future.title": "产品进度", "future.lead": "依据 @renaissxyz 主帐号原文与当前日期整理产品进度；其他帐号不会混入。", "future.pending": "主帐号既有资料正等待完成生命周期分类。", "sbt.title": "SBT 系统整理", "sbt.lead": "先确认近期与常驻的 SBT 获取方式，再阅读相关文章与官方来源。", "guide.title": "新手教学", "guide.lead": "完整保留独立教学内容；一次阅读一个章节，从左侧切换。", "media.title": "新闻与媒体", "media.lead": "官方公告、收藏与 TCG 市场情报都能回到原始贴文或来源。", "knowledge.title": "知识与工具", "knowledge.lead": "保留原本已存在的工具与入口，各自负责最适合的工作。", "records.title": "奖励、得奖者与排行榜", "records.lead": "只呈现可验证的纪录，不用推测或虚构名次。",
    "filter.all": "全部", "filter.official": "官方", "filter.community": "社群", "filter.tagged": "标记 Renaiss", "filter.active": "进行中", "filter.upcoming": "已公告", "filter.past": "过去活动", "filter.market": "市场情报", "filter.planUpcoming": "即将推出", "filter.planActive": "进行中", "filter.planCompleted": "已完成", "filter.plan.upcoming": "即将推出", "filter.plan.in_progress": "进行中", "filter.plan.completed": "已完成", "filter.plan.cancelled": "已取消", "filter.plan.not_plan": "非产品规划", "filter.plan.needs_review": "待确认", "action.refresh": "重新整理", "action.original": "查看原文", "action.hub": "阅读文章", "action.back": "返回上一区", "action.guide": "完整 SBT 新手教学", "search.placeholder": "搜寻目前资料",
    "events.empty.active": "目前没有进行中的官方活动。", "events.empty.upcoming": "目前没有进行中或已公告的官方活动。", "events.empty.past": "目前没有可显示的过去活动。",
    "card.official": "官方", "card.regional": "地区社群", "card.community": "社群", "card.active": "进行中", "card.upcoming": "已公告", "card.past": "已结束", "card.reference": "参考", "card.defaultCover": "Renaiss Community 默认封面",
    "sbt.about": "SBT 是什么？", "sbt.aboutBody": "Soulbound Token 是 Renaiss 参与与贡献的链上记录。先理解它，再依任务条件行动。", "sbt.principle": "获取原则", "sbt.principleBody": "限时 SBT 只显示有官方来源与明确有效期间的资料；常驻任务保留在完整新手教学。", "sbt.wikiLink": "前往完整新手 Wiki", "sbt.analysis": "贴文分析", "sbt.acquisition": "限时 SBT 获取", "sbt.acquisitionLead": "依近期贴文整理 SBT 名称、获取方式与时效；有明确获取动作且没有结束证据的项目标示为可获取。", "sbt.article": "SBT 相关文章", "sbt.articleLead": "点选文章卡片即可在 Hub 内阅读摘要，再对照原文。", "sbt.articleEmpty": "目前没有可在 Hub 内阅读的 SBT 文章。", "sbt.currentCatalog": "常驻 SBT 任务", "sbt.currentCatalogLead": "无活动期限、可随时完成的任务集中在完整新手 Wiki。", "sbt.availableStatus": "可获取", "sbt.difficulty": "难度", "sbt.available": "SBT 获取方式", "sbt.availableLead": "先看近期整理数量与状态，再到下方逐笔核对；常驻任务则集中在完整新手 Wiki。", "sbt.methodRecent": "近期获取线索", "sbt.methodClaimable": "已确认可获取", "sbt.methodPending": "待确认", "sbt.methodExpired": "已过期", "sbt.availableEmpty": "近期贴文尚未整理出可核对的 SBT 获取方式。", "sbt.status.pending": "待确认", "sbt.status.claimable": "可获取", "sbt.status.expired": "已过期", "sbt.legacyAvailable": "常驻可完成任务", "sbt.legacyAvailableLead": "这些是原本新手教学中的常驻任务，不会被误列为限时活动。", "sbt.none": "目前没有符合条件的官方限时 SBT 活动。",
    "records.winners": "得奖者与礼品", "records.packRank": "抽卡排行榜", "records.packRankSource": "Open Monitor · 抽卡排行 Top 200", "records.packRankLead": "排行榜资料由 Renaiss 后端直接接入 Open Monitor API，不是把使用者导向外部网站。", "records.packRankMeta": "资料来源为公开统计 · Renaiss 后端快取 5 分钟", "records.packRankAction": "查看抽卡排行榜", "records.packRankTotal": "总抽卡", "records.packRankPlayers": "玩家数", "records.packRankUpdated": "资料快照", "records.packRankPulls": "抽卡", "records.packRankLoading": "正在载入排行榜资料", "records.packRankError": "排行榜资料暂时无法取得", "records.packRankEmpty": "目前没有可显示的排行榜资料", "records.packRankNoPackBreakdown": "没有卡池分布资料", "records.packRankSnapshotUnknown": "未知", "records.packRankSourceLink": "查看来源说明", "records.winnerMissing": "尚未接入可验证的官方得奖名单。",
    "empty.unavailable": "目前没有符合来源规则的资料。", "empty.translating": "翻译仍在处理中，完成后会自动重新读取。", "guide.source": "资料来源", "guide.sourceLead": "内容整理来源：老豆子 @genekmkz 与其 Notion。", "guide.x": "X：老豆子 @genekmkz", "guide.notion": "Notion：Renaiss 指南", "guide.articleLead": "AI 分类为 guides 的教学文章会永久收录在这里，不受近期时间窗影响。", "guide.articleCount": "篇教学文章", "guide.articleEmpty": "目前没有被 AI 分类为 guides 的教学文章。",
    "community.mapTitle": "社群热点地图", "community.mapLead": "查看各地区近期互动声量与热门社群。", "community.mapTop": "目前第一名", "community.mapWaiting": "等待地区声量资料", "community.mapOpenNew": "另开完整地图", "community.mapClose": "关闭热点地图", "community.regionFilter": "按社群帐号地区筛选", "community.regionAll": "全部地区",
    "pagination.label": "内容分页", "pagination.previous": "上一页", "pagination.next": "下一页", "pagination.page": "第",
    "article.published": "发布", "article.timeline": "内容日期", "article.facts": "活动资讯", "article.fact.schedule": "时间", "article.fact.location": "地点", "article.fact.participation": "参与方式", "article.fact.reward": "奖励", "article.fact.audience": "适合对象", "article.highlights": "重点", "article.analysis": "完整整理", "article.details": "详细内容", "article.sbt": "SBT 资讯", "article.plan": "产品进度判定", "article.sourceText": "原始内容", "article.partial": "暂时无法取得完整原文，以下仅保留可验证的贴文预览。", "article.tags": "文章分类",
  },
  en: {
    "card.pinned": "Pinned",
    "app.legacy": "Legacy aggregator", "app.open": "Open Renaiss", "app.source": "Community intelligence", "app.wiki": "Open beginner Wiki", "app.agent": "Ask Renaiss Agent", "auth.login": "Sign in to edit", "auth.logout": "Sign out", "auth.account": "Renaiss account", "auth.checking": "Checking sign-in",
    "nav.overview": "Overview", "nav.events": "Events", "nav.official": "Official updates", "nav.feed": "Community feed", "nav.future": "Product progress", "nav.sbt": "SBT", "nav.profile": "Profile", "nav.guide": "Beginner guide", "nav.records": "Rewards and records", "nav.media": "News and media", "nav.knowledge": "Knowledge and tools", "nav.manage": "Content management",
    "status.loading": "Loading live Renaiss intelligence", "status.live": "Live data", "status.error": "Unable to load live data", "status.cards": "items", "status.translating": "Translation in progress",
    "overview.lead": "A single entry point for verified official events, community signals, limited SBTs, and the complete guide.", "overview.events": "View events", "overview.feed": "Community feed", "overview.source": "Source", "overview.happening": "Happening now", "overview.allEvents": "All events", "overview.limitedSbt": "Limited SBT campaigns", "overview.allSbt": "Full SBT list", "overview.limitedEmpty": "There are no official limited SBT campaigns with a clear active deadline. See the beginner guide for evergreen tasks.", "overview.signals": "Signals to watch", "overview.allSignals": "All updates", "overview.start": "Start here",
    "overview.route.official": "Official updates", "overview.route.officialSub": "Official announcements and product updates, separate from events", "overview.route.feed": "Community feed", "overview.route.feedSub": "Community posts and Renaiss-tagged discussion only", "overview.route.events": "Events", "overview.route.eventsSub": "See official Renaiss event status only", "overview.route.future": "Product progress", "overview.route.futureSub": "AI-classified lifecycle based on source text and dates", "overview.route.sbt": "SBT", "overview.route.sbtSub": "Limited campaigns, articles, and task entry points", "overview.route.records": "Rewards and records", "overview.route.recordsSub": "Verified results and rankings only", "overview.route.guide": "Beginner guide", "overview.route.guideSub": "All original chapters and tools",
    "official.title": "Official updates", "official.lead": "Official announcements and product updates are collected here. Established campaigns stay on the Events page.", "official.aiSummary": "AI summary", "official.summaryEyebrow": "AI WEEKLY BRIEF", "official.summaryTitle": "Official seven-day summary", "official.summaryClose": "Close official summary", "official.summaryUnavailable": "The seven-day summary is not ready yet. Refresh again shortly.", "feed.title": "Community feed", "feed.lead": "Community posts and Renaiss-tagged discussion only. Official-account content is kept separate.", "events.title": "Events", "events.lead": "Events from the main Renaiss account and regional community accounts are collected here. The region matching the current language is gold; all others use a consistent blue marker.", "future.title": "Product progress", "future.lead": "Product progress is organized from @renaissxyz source posts and the current date; other accounts are excluded.", "future.pending": "Existing main-account records are waiting for lifecycle classification.", "sbt.title": "SBT system index", "sbt.lead": "Review recent and evergreen SBT acquisition paths before reading related articles and official sources.", "guide.title": "Beginner guide", "guide.lead": "The complete independent guide is retained. Read one chapter at a time from the left navigation.", "media.title": "News and media", "media.lead": "Official announcements, collectible updates, and TCG market signals always link to their original source.", "knowledge.title": "Knowledge and tools", "knowledge.lead": "Existing tools and entry points stay separate so each can do the job it is designed for.", "records.title": "Rewards, winners, and rankings", "records.lead": "Only verifiable records appear here. No inferred or fabricated rankings.",
    "filter.all": "All", "filter.official": "Official", "filter.community": "Community", "filter.tagged": "Tagged Renaiss", "filter.active": "Active", "filter.upcoming": "Announced", "filter.past": "Past", "filter.market": "Market", "filter.planUpcoming": "Upcoming", "filter.planActive": "In progress", "filter.planCompleted": "Completed", "filter.plan.upcoming": "Upcoming", "filter.plan.in_progress": "In progress", "filter.plan.completed": "Completed", "filter.plan.cancelled": "Cancelled", "filter.plan.not_plan": "Not a product plan", "filter.plan.needs_review": "Needs review", "action.refresh": "Refresh", "action.original": "Open source", "action.hub": "Read article", "action.back": "Back to previous section", "action.guide": "Complete SBT beginner guide", "search.placeholder": "Search current data",
    "events.empty.active": "There are no active official events right now.", "events.empty.upcoming": "There are no active or announced official events right now.", "events.empty.past": "There are no past events to display.",
    "card.official": "Official", "card.regional": "Regional community", "card.community": "Community", "card.active": "Active", "card.upcoming": "Announced", "card.past": "Ended", "card.reference": "Reference", "card.defaultCover": "Renaiss Community default cover",
    "sbt.about": "What is an SBT?", "sbt.aboutBody": "Soulbound Tokens are on-chain records of participation and contribution in Renaiss. Understand the context before acting on a task.", "sbt.principle": "Earning principle", "sbt.principleBody": "Limited SBTs require an official source and an explicit active period. Evergreen tasks remain in the full beginner guide.", "sbt.wikiLink": "Open the complete beginner Wiki", "sbt.analysis": "Post analysis", "sbt.acquisition": "Limited SBT acquisition", "sbt.acquisitionLead": "Recent posts are organized by SBT name, acquisition method, and timing. Items with a clear action and no evidence of closure are marked available.", "sbt.article": "SBT articles", "sbt.articleLead": "Select an article card to read its summary in the Hub, then compare the source.", "sbt.articleEmpty": "No SBT articles are currently available for in-Hub reading.", "sbt.currentCatalog": "Evergreen SBT tasks", "sbt.currentCatalogLead": "Tasks without an event deadline are collected in the complete beginner Wiki.", "sbt.availableStatus": "Available", "sbt.difficulty": "Difficulty", "sbt.available": "SBT acquisition paths", "sbt.availableLead": "Review the recent counts and status first, then verify each item below. Evergreen tasks remain in the complete beginner Wiki.", "sbt.methodRecent": "Recent earning signals", "sbt.methodClaimable": "Confirmed available", "sbt.methodPending": "Pending", "sbt.methodExpired": "Expired", "sbt.availableEmpty": "Recent posts do not provide an SBT acquisition path that can be checked against a source.", "sbt.status.pending": "Pending", "sbt.status.claimable": "Available", "sbt.status.expired": "Expired", "sbt.legacyAvailable": "Evergreen tasks", "sbt.legacyAvailableLead": "These are original beginner-guide tasks and are not represented as limited campaigns.", "sbt.none": "There are no qualifying official limited SBT campaigns right now.",
    "records.winners": "Winners and gifts", "records.packRank": "Pack-opening leaderboard", "records.packRankSource": "Open Monitor · Top 200 pack openers", "records.packRankLead": "The Renaiss backend reads the Open Monitor API directly, so this is data inside the Hub rather than a link-out page.", "records.packRankMeta": "Public statistics · Cached by the Renaiss backend for 5 minutes", "records.packRankAction": "Open pack leaderboard", "records.packRankTotal": "Total pulls", "records.packRankPlayers": "Players", "records.packRankUpdated": "Snapshot", "records.packRankPulls": "pulls", "records.packRankLoading": "Loading leaderboard data", "records.packRankError": "Leaderboard data is temporarily unavailable", "records.packRankEmpty": "No leaderboard data is available right now", "records.packRankNoPackBreakdown": "No pack breakdown", "records.packRankSnapshotUnknown": "Unknown", "records.packRankSourceLink": "View source details", "records.winnerMissing": "No verifiable official winner list has been connected yet.",
    "empty.unavailable": "No records match the current source rules.", "empty.translating": "Translation is still processing and will be loaded again when ready.", "guide.source": "Sources", "guide.sourceLead": "Guide materials are credited to @genekmkz and the associated Notion guide.", "guide.x": "X: @genekmkz", "guide.notion": "Notion: Renaiss Guide", "guide.articleLead": "Articles classified as guides by AI remain available here without a recency or expiry window.", "guide.articleCount": "guide articles", "guide.articleEmpty": "No articles are currently classified as guides by AI.",
    "community.mapTitle": "Community pulse map", "community.mapLead": "See recent regional engagement and the most active community.", "community.mapTop": "Current leader", "community.mapWaiting": "Waiting for regional metrics", "community.mapOpenNew": "Open full map", "community.mapClose": "Close pulse map", "community.regionFilter": "Filter by community account region", "community.regionAll": "All regions",
    "pagination.label": "Content pages", "pagination.previous": "Previous", "pagination.next": "Next", "pagination.page": "Page",
    "article.published": "Published", "article.timeline": "Content date", "article.facts": "Event information", "article.fact.schedule": "Schedule", "article.fact.location": "Location", "article.fact.participation": "How to join", "article.fact.reward": "Reward", "article.fact.audience": "Audience", "article.highlights": "Highlights", "article.analysis": "Full analysis", "article.details": "Details", "article.sbt": "SBT information", "article.plan": "Product progress decision", "article.sourceText": "Source content", "article.partial": "The full source is temporarily unavailable. Only the verified post preview is shown below.", "article.tags": "Article categories",
  },
  ko: {
    "card.pinned": "고정",
    "app.legacy": "기존 애그리게이터", "app.open": "Open Renaiss", "app.source": "커뮤니티 인텔리전스", "app.wiki": "초보자 Wiki 열기", "app.agent": "Renaiss Agent에게 묻기", "auth.login": "편집 로그인", "auth.logout": "로그아웃", "auth.account": "Renaiss 계정", "auth.checking": "로그인 확인 중",
    "nav.overview": "개요", "nav.events": "이벤트", "nav.official": "공식 업데이트", "nav.feed": "커뮤니티 피드", "nav.future": "제품 진행", "nav.sbt": "SBT", "nav.profile": "Profile", "nav.guide": "초보자 가이드", "nav.records": "보상 및 기록", "nav.media": "뉴스 및 미디어", "nav.knowledge": "지식 및 도구", "nav.manage": "콘텐츠 관리",
    "status.loading": "실시간 Renaiss 정보를 불러오는 중", "status.live": "실시간 데이터", "status.error": "실시간 데이터를 불러올 수 없습니다", "status.cards": "개 항목", "status.translating": "번역 처리 중",
    "overview.lead": "검증된 공식 이벤트, 커뮤니티 신호, 기간 한정 SBT, 전체 가이드를 하나의 진입점에 모았습니다.", "overview.events": "이벤트 보기", "overview.feed": "커뮤니티 피드", "overview.source": "출처", "overview.happening": "지금 진행 중", "overview.allEvents": "모든 이벤트", "overview.limitedSbt": "기간 한정 SBT 캠페인", "overview.allSbt": "전체 SBT 목록", "overview.limitedEmpty": "명확한 마감일이 있는 공식 기간 한정 SBT 캠페인이 없습니다. 상시 과제는 초보자 가이드에서 확인하세요.", "overview.signals": "주목할 신호", "overview.allSignals": "모든 업데이트", "overview.start": "여기서 시작",
    "overview.route.official": "공식 업데이트", "overview.route.officialSub": "이벤트와 분리된 공식 공지 및 제품 업데이트", "overview.route.feed": "커뮤니티 피드", "overview.route.feedSub": "커뮤니티 게시물과 Renaiss 태그 토론만 보기", "overview.route.events": "이벤트", "overview.route.eventsSub": "공식 Renaiss 이벤트 상태만 보기", "overview.route.future": "제품 진행", "overview.route.futureSub": "AI가 원문과 날짜로 수명 주기를 분류", "overview.route.sbt": "SBT", "overview.route.sbtSub": "기간 한정 캠페인, 글, 과제 진입점", "overview.route.records": "보상 및 기록", "overview.route.recordsSub": "검증된 결과와 순위만 보기", "overview.route.guide": "초보자 가이드", "overview.route.guideSub": "원래의 모든 장과 도구를 보존",
    "official.title": "공식 업데이트", "official.lead": "공식 공지와 제품 업데이트를 모았습니다. 확정된 캠페인은 이벤트 페이지에서 확인하세요.", "official.aiSummary": "AI 요약", "official.summaryEyebrow": "AI WEEKLY BRIEF", "official.summaryTitle": "최근 7일 공식 요약", "official.summaryClose": "공식 요약 닫기", "official.summaryUnavailable": "최근 7일 요약이 아직 준비되지 않았습니다. 잠시 후 새로고침해 주세요.", "feed.title": "커뮤니티 피드", "feed.lead": "커뮤니티 게시물과 Renaiss 태그 토론만 표시합니다. 공식 계정 내용은 별도로 분리합니다.", "events.title": "이벤트", "events.lead": "Renaiss 메인 계정과 지역 커뮤니티 계정의 이벤트를 모았습니다. 현재 언어에 해당하는 지역은 금색, 다른 지역은 동일한 파란색으로 표시합니다.", "future.title": "제품 진행", "future.lead": "@renaissxyz 메인 계정 원문과 현재 날짜를 기준으로 제품 진행을 정리하며 다른 계정은 제외합니다.", "future.pending": "메인 계정의 기존 데이터가 수명 주기 분류를 기다리고 있습니다.", "sbt.title": "SBT 시스템 정리", "sbt.lead": "최근 및 상시 SBT 획득 경로를 확인한 뒤 관련 글과 공식 출처를 읽어보세요.", "guide.title": "초보자 가이드", "guide.lead": "독립된 전체 가이드를 보존합니다. 왼쪽에서 한 번에 한 장씩 읽으세요.", "media.title": "뉴스 및 미디어", "media.lead": "공식 공지, 컬렉터블 및 TCG 시장 정보는 원문으로 돌아갈 수 있습니다.", "knowledge.title": "지식 및 도구", "knowledge.lead": "기존 도구와 진입점은 각자 가장 적합한 역할을 할 수 있도록 분리합니다.", "records.title": "보상, 수상자 및 순위", "records.lead": "검증 가능한 기록만 표시합니다. 추정하거나 꾸며낸 순위는 표시하지 않습니다.",
    "filter.all": "전체", "filter.official": "공식", "filter.community": "커뮤니티", "filter.tagged": "Renaiss 태그", "filter.active": "진행 중", "filter.upcoming": "공지됨", "filter.past": "과거", "filter.market": "시장", "filter.planUpcoming": "출시 예정", "filter.planActive": "진행 중", "filter.planCompleted": "완료", "filter.plan.upcoming": "출시 예정", "filter.plan.in_progress": "진행 중", "filter.plan.completed": "완료", "filter.plan.cancelled": "취소됨", "filter.plan.not_plan": "제품 계획 아님", "filter.plan.needs_review": "확인 필요", "action.refresh": "새로고침", "action.original": "원문 보기", "action.hub": "글 읽기", "action.back": "이전 섹션으로", "action.guide": "전체 SBT 초보자 가이드", "search.placeholder": "현재 데이터 검색",
    "events.empty.active": "현재 진행 중인 공식 이벤트가 없습니다.", "events.empty.upcoming": "현재 진행 중이거나 공지된 공식 이벤트가 없습니다.", "events.empty.past": "표시할 지난 이벤트가 없습니다.",
    "card.official": "공식", "card.regional": "지역 커뮤니티", "card.community": "커뮤니티", "card.active": "진행 중", "card.upcoming": "공지됨", "card.past": "종료됨", "card.reference": "참고", "card.defaultCover": "Renaiss Community 기본 표지",
    "sbt.about": "SBT란?", "sbt.aboutBody": "Soulbound Token은 Renaiss에서의 참여와 기여를 보여주는 온체인 기록입니다. 과제 전에 맥락을 이해하세요.", "sbt.principle": "획득 원칙", "sbt.principleBody": "기간 한정 SBT는 공식 출처와 명확한 유효 기간이 있어야 합니다. 상시 과제는 전체 초보자 가이드에 남깁니다.", "sbt.wikiLink": "전체 초보자 Wiki 열기", "sbt.analysis": "게시물 분석", "sbt.acquisition": "기간 한정 SBT 획득", "sbt.acquisitionLead": "최근 게시물을 SBT 이름, 획득 방법, 기간 정보로 정리합니다. 명확한 행동이 있고 종료 근거가 없는 항목은 획득 가능으로 표시합니다.", "sbt.article": "SBT 관련 글", "sbt.articleLead": "글 카드를 선택하면 Hub에서 요약을 읽고 원문과 대조할 수 있습니다.", "sbt.articleEmpty": "현재 Hub에서 읽을 수 있는 SBT 글이 없습니다.", "sbt.currentCatalog": "상시 SBT 과제", "sbt.currentCatalogLead": "이벤트 마감이 없이 언제든 완료할 수 있는 과제는 전체 초보자 Wiki에 모았습니다.", "sbt.availableStatus": "획득 가능", "sbt.difficulty": "난이도", "sbt.available": "SBT 획득 방법", "sbt.availableLead": "먼저 최근 정리 수와 상태를 확인한 뒤 아래 항목을 검증하세요. 상시 과제는 전체 초보자 Wiki에 있습니다.", "sbt.methodRecent": "최근 획득 단서", "sbt.methodClaimable": "획득 가능 확인", "sbt.methodPending": "확인 필요", "sbt.methodExpired": "만료됨", "sbt.availableEmpty": "최근 게시물에서 출처와 대조할 수 있는 SBT 획득 방법을 찾지 못했습니다.", "sbt.status.pending": "확인 필요", "sbt.status.claimable": "획득 가능", "sbt.status.expired": "만료됨", "sbt.legacyAvailable": "상시 가능 과제", "sbt.legacyAvailableLead": "원래 초보자 가이드의 과제이며 기간 한정 캠페인으로 표시하지 않습니다.", "sbt.none": "현재 조건을 충족하는 공식 기간 한정 SBT 캠페인이 없습니다.",
    "records.winners": "수상자와 선물", "records.packRank": "팩 오픈 랭킹", "records.packRankSource": "Open Monitor · 팩 오픈 Top 200", "records.packRankLead": "Renaiss 백엔드가 Open Monitor API를 직접 읽습니다. 외부 사이트로 이동하는 링크가 아니라 Hub 안의 데이터입니다.", "records.packRankMeta": "공개 통계 · Renaiss 백엔드 5분 캐시", "records.packRankAction": "팩 오픈 랭킹 열기", "records.packRankTotal": "총 오픈", "records.packRankPlayers": "플레이어", "records.packRankUpdated": "스냅샷", "records.packRankPulls": "오픈", "records.packRankLoading": "랭킹 데이터를 불러오는 중", "records.packRankError": "랭킹 데이터를 잠시 불러올 수 없습니다", "records.packRankEmpty": "현재 표시할 랭킹 데이터가 없습니다", "records.packRankNoPackBreakdown": "팩 분포 없음", "records.packRankSnapshotUnknown": "알 수 없음", "records.packRankSourceLink": "출처 상세 보기", "records.winnerMissing": "검증 가능한 공식 수상자 명단이 아직 연결되지 않았습니다.",
    "empty.unavailable": "현재 출처 규칙에 맞는 기록이 없습니다.", "empty.translating": "번역이 아직 처리 중이며 준비되면 다시 불러옵니다.", "guide.source": "출처", "guide.sourceLead": "가이드 자료 출처: @genekmkz와 해당 Notion 가이드.", "guide.x": "X: @genekmkz", "guide.notion": "Notion: Renaiss Guide", "guide.articleLead": "AI가 guides로 분류한 가이드 글은 최신 기간이나 만료 기준 없이 계속 보관됩니다.", "guide.articleCount": "개 가이드 글", "guide.articleEmpty": "현재 AI가 guides로 분류한 글이 없습니다.",
    "community.mapTitle": "커뮤니티 펄스 지도", "community.mapLead": "지역별 최근 참여도와 가장 활발한 커뮤니티를 확인하세요.", "community.mapTop": "현재 1위", "community.mapWaiting": "지역 지표 대기 중", "community.mapOpenNew": "전체 지도 열기", "community.mapClose": "펄스 지도 닫기", "community.regionFilter": "커뮤니티 계정 지역별 필터", "community.regionAll": "모든 지역",
    "pagination.label": "콘텐츠 페이지", "pagination.previous": "이전", "pagination.next": "다음", "pagination.page": "페이지",
    "article.published": "게시", "article.timeline": "콘텐츠 날짜", "article.facts": "이벤트 정보", "article.fact.schedule": "시간", "article.fact.location": "장소", "article.fact.participation": "참여 방법", "article.fact.reward": "보상", "article.fact.audience": "대상", "article.highlights": "핵심", "article.analysis": "전체 정리", "article.details": "상세 내용", "article.sbt": "SBT 정보", "article.plan": "제품 진행 판정", "article.sourceText": "원문 내용", "article.partial": "전체 원문을 일시적으로 가져오지 못해 검증된 게시물 미리보기만 표시합니다.", "article.tags": "글 분류",
  },
};

const officialCategoryCopy: Record<Language, Record<string, string>> = {
  "zh-Hant": {
    "filter.allOfficialCategories": "全部分類",
    "events.lead": "活動牆只顯示活動日前 14 天至結束後 14 天；進行中與人工置頂活動不受此限制。後端判定為重複的貼文不會再次顯示。",
    "official.lead": "依分類查看官方公告與產品更新；已成立或置頂的重大活動請到活動頁查看。",
    "official.categoryFilter": "官方動態分類",
    "future.lead": "依各官方分類的原文與目前日期整理產品進度，也可單獨查看特定分類。",
    "future.pending": "官方分類的既有資料正等待完成生命週期分類。",
    "future.projectFilter": "產品分類",
    "future.statusFilter": "內容類型與進度",
    "future.countGuide": "帳號旁的數字＝近 30 天官方動態，不是里程碑數。里程碑規則：即將推出需有未來日期、進行中保留 14 天、已完成需有明確日期且保留 30 天；同產品、日期與階段的重複公告只顯示一次。Index 的明確合作公告會獨立列在合作夥伴。",
    "future.partnership": "合作夥伴",
    "future.partnershipLead": "只列出 @renaiss_index 原文中明確宣布的合作對象；產品介紹與市場週報仍保留在近期官方動態。",
    "future.noMilestones": "目前沒有可驗證的產品里程碑",
    "future.empty": "這個分類目前沒有符合所選狀態的產品進度。",
    "future.empty.otherStatus": "這個分類在其他狀態仍有進度，可切換上方狀態查看；一般更新則保留在官方動態。",
    "future.empty.withUpdates": "一般公告、週報與功能介紹仍保留在官方動態，不會被誤列為產品進度。",
    "future.empty.noUpdates": "目前也沒有可顯示的官方動態，資料更新後會自動出現。",
    "future.openOfficial": "前往官方動態",
    "future.recentEyebrow": "OFFICIAL UPDATES",
    "future.recentTitle": "近期官方動態",
    "future.recentLead": "以下保留這個帳號近 30 天的真實動態；沒有符合進度時間規則的內容不會被誤列為里程碑。",
    "future.recentStatus": "一般更新",
  },
  "zh-Hans": {
    "filter.allOfficialCategories": "全部分类",
    "events.lead": "活动墙只显示活动日前 14 天至结束后 14 天；进行中与人工置顶活动不受此限制。后端判定为重复的贴文不会再次显示。",
    "official.lead": "依分类查看官方公告与产品更新；已成立或置顶的重大活动请到活动页查看。",
    "official.categoryFilter": "官方动态分类",
    "future.lead": "依据各官方分类原文与当前日期整理产品进度，也可单独查看特定分类。",
    "future.pending": "官方分类的既有资料正等待完成生命周期分类。",
    "future.projectFilter": "产品分类",
    "future.statusFilter": "内容类型与进度",
    "future.countGuide": "账号旁的数字＝近 30 天官方动态，不是里程碑数。里程碑规则：即将推出需有未来日期、进行中保留 14 天、已完成需有明确日期且保留 30 天；同产品、日期与阶段的重复公告只显示一次。Index 的明确合作公告会独立列在合作伙伴。",
    "future.partnership": "合作伙伴",
    "future.partnershipLead": "只列出 @renaiss_index 原文中明确宣布的合作对象；产品介绍与市场周报仍保留在近期官方动态。",
    "future.noMilestones": "目前没有可验证的产品里程碑",
    "future.empty": "这个分类目前没有符合所选状态的产品进度。",
    "future.empty.otherStatus": "这个分类在其他状态仍有进度，可切换上方状态查看；一般更新则保留在官方动态。",
    "future.empty.withUpdates": "一般公告、周报与功能介绍仍保留在官方动态，不会被误列为产品进度。",
    "future.empty.noUpdates": "目前也没有可显示的官方动态，资料更新后会自动出现。",
    "future.openOfficial": "前往官方动态",
    "future.recentEyebrow": "OFFICIAL UPDATES",
    "future.recentTitle": "近期官方动态",
    "future.recentLead": "以下保留这个账号近 30 天的真实动态；没有符合进度时间规则的内容不会被误列为里程碑。",
    "future.recentStatus": "一般更新",
  },
  en: {
    "filter.allOfficialCategories": "All categories",
    "events.lead": "The event wall shows events from 14 days before they start through 14 days after they end. Active and manually pinned events remain visible. Posts marked duplicate by the backend are not shown again.",
    "official.lead": "Browse announcements and product updates by category. Established or pinned campaigns stay on the Events page.",
    "official.categoryFilter": "Official update categories",
    "future.lead": "Product progress is organized from each official category's source posts and the current date, with category filtering.",
    "future.pending": "Existing official-category records are waiting for lifecycle classification.",
    "future.projectFilter": "Product category",
    "future.statusFilter": "Content type and progress",
    "future.countGuide": "Account counts cover 30 days of official updates; they are not milestone totals. Upcoming needs a future date, In progress stays 14 days, and dated Completed milestones stay 30 days. Repeated announcements for the same product, date, and phase appear once. Explicit Index partnerships appear separately.",
    "future.partnership": "Partners",
    "future.partnershipLead": "Only partners explicitly announced in @renaiss_index source posts appear here. Product explainers and market reports remain under recent official updates.",
    "future.noMilestones": "No verifiable product milestones right now",
    "future.empty": "This category has no product progress matching the selected status.",
    "future.empty.otherStatus": "This category has progress in other statuses. Switch the status above to view it; general updates remain in Official updates.",
    "future.empty.withUpdates": "General announcements, reports, and feature introductions remain in Official updates instead of being mislabeled as product progress.",
    "future.empty.noUpdates": "There are no official updates to show yet. New data will appear automatically.",
    "future.openOfficial": "Open Official updates",
    "future.recentEyebrow": "OFFICIAL UPDATES",
    "future.recentTitle": "Recent official updates",
    "future.recentLead": "These are real updates from this account in the last 30 days. Items outside the timeline rules are not mislabeled as milestones.",
    "future.recentStatus": "General update",
  },
  ko: {
    "filter.allOfficialCategories": "전체 분류",
    "events.lead": "이벤트 월은 시작 14일 전부터 종료 14일 후까지 표시합니다. 진행 중이거나 수동으로 고정한 이벤트는 계속 표시되며, 백엔드에서 중복으로 판정한 게시물은 다시 표시하지 않습니다.",
    "official.lead": "분류별 공식 공지와 제품 업데이트를 확인하세요. 확정되었거나 고정된 캠페인은 이벤트 페이지에 표시됩니다.",
    "official.categoryFilter": "공식 업데이트 분류",
    "future.lead": "각 공식 분류의 원문과 현재 날짜를 기준으로 제품 진행을 정리하고 분류별로 필터링합니다.",
    "future.pending": "공식 분류의 기존 데이터가 수명 주기 분류를 기다리고 있습니다.",
    "future.projectFilter": "제품 분류",
    "future.statusFilter": "콘텐츠 유형 및 진행 상태",
    "future.countGuide": "계정 숫자는 최근 30일 공식 업데이트 수이며 마일스톤 합계가 아닙니다. 출시 예정은 미래 날짜가 필요하고, 진행 중은 14일, 날짜가 있는 완료 항목은 30일간 표시됩니다. 같은 제품, 날짜, 단계의 반복 공지는 한 번만 표시됩니다. Index의 명확한 파트너십 공지는 별도로 표시됩니다.",
    "future.partnership": "파트너",
    "future.partnershipLead": "@renaiss_index 원문에서 명확히 발표한 파트너만 표시합니다. 제품 설명과 시장 보고서는 최근 공식 업데이트에 유지됩니다.",
    "future.noMilestones": "현재 확인 가능한 제품 마일스톤이 없습니다",
    "future.empty": "이 분류에는 선택한 상태와 일치하는 제품 진행이 없습니다.",
    "future.empty.otherStatus": "이 분류에는 다른 상태의 진행이 있습니다. 위에서 상태를 전환해 확인하고, 일반 업데이트는 공식 업데이트에서 볼 수 있습니다.",
    "future.empty.withUpdates": "일반 공지, 주간 보고서, 기능 소개는 제품 진행으로 잘못 표시하지 않고 공식 업데이트에 유지합니다.",
    "future.empty.noUpdates": "현재 표시할 공식 업데이트도 없습니다. 새 데이터가 준비되면 자동으로 나타납니다.",
    "future.openOfficial": "공식 업데이트 보기",
    "future.recentEyebrow": "OFFICIAL UPDATES",
    "future.recentTitle": "최근 공식 업데이트",
    "future.recentLead": "이 계정의 최근 30일 실제 업데이트입니다. 기간 규칙을 충족하지 않는 내용은 마일스톤으로 잘못 표시하지 않습니다.",
    "future.recentStatus": "일반 업데이트",
  },
};

const productDynamicsCopy: Record<Language, Record<string, string>> = {
  "zh-Hant": {
    "future.lead": "把同一產品散落的官方貼文串成時間線，直接查看目前狀態、最新變化與原始證據。",
    "product.summaryLabel": "產品動態摘要",
    "product.products": "項產品",
    "product.updates": "次狀態變化",
    "product.families": "個產品家族",
    "product.productsLabel": "產品數",
    "product.updatesLabel": "狀態變化",
    "product.familiesLabel": "產品家族",
    "product.method": "狀態只由最新的官方產品事件更新；市場結果、活動與說明文保留為相關資料，不會改寫產品目前狀態。",
    "product.familyFilter": "依產品家族篩選",
    "product.familyEyebrow": "PRODUCT FAMILY",
    "product.timeline": "產品時間線",
    "product.showTimeline": "查看完整時間線",
    "product.lastVerified": "最後官方證據",
    "product.related": "相關官方資料",
    "product.relatedLead": "這些貼文提到或展示產品，但沒有足夠的狀態變化證據，因此不計為產品里程碑。",
    "product.candidateLead": "目前只有相關官方訊號，尚未取得足夠證據建立產品里程碑。",
    "product.noProducts": "目前沒有可整理的官方產品動態",
    "product.mode.experimental": "實驗原型",
    "product.mode.candidate": "候選產品",
    "product.unmappedTitle": "待歸類的產品證據",
    "product.unmappedLead": "這些官方貼文完整通過四題判斷，但尚未有可持續沿用的產品身分，因此先保留為證據，不建立假產品。",
    "product.family.fair": "Fair & RIP",
    "product.family.gacha": "Infinite Gacha",
    "product.family.packs": "限量卡包",
    "product.family.sbt": "SBT 與獎勵",
    "product.family.index": "Renaiss Index",
    "product.family.tech": "Tech Lab",
    "product.family.store": "商店兌換",
    "product.family.platform": "平台能力與規則",
    "product.family.vinci": "Vinci World",
    "product.status.candidate": "等待更多證據",
    "product.status.proposed": "提案已發布",
    "product.status.upcoming": "即將推出",
    "product.status.live": "已上線",
    "product.status.updated": "持續更新",
    "product.status.maintenance": "最後已知維護中",
    "product.status.adopted": "已全面採用",
    "product.status.sold_out": "已售罄",
    "product.status.claim_open": "開放領取",
    "product.status.completed": "本輪已完成",
    "product.status.prototype": "原型展示",
    "product.status.expanding": "合作建設中",
    "product.status.restocked": "已完成補貨",
    "product.update.proposal": "提案",
    "product.update.implementation": "首個產品實作",
    "product.update.adoption": "全面採用",
    "product.update.launch": "正式上線",
    "product.update.content_update": "內容或功能更新",
    "product.update.maintenance": "維護",
    "product.update.restock": "補貨",
    "product.update.sold_out": "售罄",
    "product.update.claim_open": "開放領取",
    "product.update.policy_change": "規則調整",
    "product.update.partnership": "合作建設",
    "product.update.prototype": "原型公開",
    "product.update.announcement": "發布預告",
    "product.update.milestone": "產品里程碑",
  },
  "zh-Hans": {
    "future.lead": "把同一产品散落的官方贴文串成时间线，直接查看当前状态、最新变化与原始证据。",
    "product.summaryLabel": "产品动态摘要",
    "product.products": "项产品",
    "product.updates": "次状态变化",
    "product.families": "个产品家族",
    "product.productsLabel": "产品数",
    "product.updatesLabel": "状态变化",
    "product.familiesLabel": "产品家族",
    "product.method": "状态只由最新的官方产品事件更新；市场结果、活动与说明文保留为相关资料，不会改写产品当前状态。",
    "product.familyFilter": "按产品家族筛选",
    "product.familyEyebrow": "PRODUCT FAMILY",
    "product.timeline": "产品时间线",
    "product.showTimeline": "查看完整时间线",
    "product.lastVerified": "最后官方证据",
    "product.related": "相关官方资料",
    "product.relatedLead": "这些贴文提到或展示产品，但没有足够的状态变化证据，因此不计为产品里程碑。",
    "product.candidateLead": "目前只有相关官方讯号，尚未取得足够证据建立产品里程碑。",
    "product.noProducts": "目前没有可整理的官方产品动态",
    "product.mode.experimental": "实验原型",
    "product.mode.candidate": "候选产品",
    "product.unmappedTitle": "待归类的产品证据",
    "product.unmappedLead": "这些官方贴文完整通过四题判断，但尚未有可持续沿用的产品身份，因此先保留为证据，不建立假产品。",
    "product.family.fair": "Fair & RIP",
    "product.family.gacha": "Infinite Gacha",
    "product.family.packs": "限量卡包",
    "product.family.sbt": "SBT 与奖励",
    "product.family.index": "Renaiss Index",
    "product.family.tech": "Tech Lab",
    "product.family.store": "商店兑换",
    "product.family.platform": "平台能力与规则",
    "product.family.vinci": "Vinci World",
    "product.status.candidate": "等待更多证据",
    "product.status.proposed": "提案已发布",
    "product.status.upcoming": "即将推出",
    "product.status.live": "已上线",
    "product.status.updated": "持续更新",
    "product.status.maintenance": "最后已知维护中",
    "product.status.adopted": "已全面采用",
    "product.status.sold_out": "已售罄",
    "product.status.claim_open": "开放领取",
    "product.status.completed": "本轮已完成",
    "product.status.prototype": "原型展示",
    "product.status.expanding": "合作建设中",
    "product.status.restocked": "已完成补货",
    "product.update.proposal": "提案",
    "product.update.implementation": "首个产品实作",
    "product.update.adoption": "全面采用",
    "product.update.launch": "正式上线",
    "product.update.content_update": "内容或功能更新",
    "product.update.maintenance": "维护",
    "product.update.restock": "补货",
    "product.update.sold_out": "售罄",
    "product.update.claim_open": "开放领取",
    "product.update.policy_change": "规则调整",
    "product.update.partnership": "合作建设",
    "product.update.prototype": "原型公开",
    "product.update.announcement": "发布预告",
    "product.update.milestone": "产品里程碑",
  },
  en: {
    "future.lead": "Turn scattered official posts about the same product into one timeline with its current state, latest change, and source evidence.",
    "product.summaryLabel": "Product pulse summary",
    "product.products": "products",
    "product.updates": "state changes",
    "product.families": "product families",
    "product.productsLabel": "Products",
    "product.updatesLabel": "State changes",
    "product.familiesLabel": "Product families",
    "product.method": "Only the latest verified official product event changes the current state. Market results, events, and explainers stay as related context.",
    "product.familyFilter": "Filter by product family",
    "product.familyEyebrow": "PRODUCT FAMILY",
    "product.timeline": "Product timeline",
    "product.showTimeline": "Open full timeline",
    "product.lastVerified": "Latest official evidence",
    "product.related": "Related official context",
    "product.relatedLead": "These posts mention or demonstrate the product but do not provide enough evidence of a state change to count as milestones.",
    "product.candidateLead": "Official signals exist, but there is not enough evidence yet to establish a product milestone.",
    "product.noProducts": "No official product dynamics are ready",
    "product.mode.experimental": "Experimental prototype",
    "product.mode.candidate": "Candidate product",
    "product.unmappedTitle": "Unmapped product evidence",
    "product.unmappedLead": "These official posts pass all four evidence checks but lack a durable product identity, so they remain evidence instead of becoming invented products.",
    "product.family.fair": "Fair & RIP",
    "product.family.gacha": "Infinite Gacha",
    "product.family.packs": "Limited Packs",
    "product.family.sbt": "SBT & Rewards",
    "product.family.index": "Renaiss Index",
    "product.family.tech": "Tech Lab",
    "product.family.store": "Store Redemption",
    "product.family.platform": "Platform Capabilities & Policy",
    "product.family.vinci": "Vinci World",
    "product.status.candidate": "Awaiting evidence",
    "product.status.proposed": "Proposal published",
    "product.status.upcoming": "Upcoming",
    "product.status.live": "Live",
    "product.status.updated": "Actively updated",
    "product.status.maintenance": "Last known in maintenance",
    "product.status.adopted": "Fully adopted",
    "product.status.sold_out": "Sold out",
    "product.status.claim_open": "Claim open",
    "product.status.completed": "Round completed",
    "product.status.prototype": "Prototype showcase",
    "product.status.expanding": "Integration in progress",
    "product.status.restocked": "Restock completed",
    "product.update.proposal": "Proposal",
    "product.update.implementation": "First product implementation",
    "product.update.adoption": "Full adoption",
    "product.update.launch": "Launch",
    "product.update.content_update": "Content or feature update",
    "product.update.maintenance": "Maintenance",
    "product.update.restock": "Restock",
    "product.update.sold_out": "Sold out",
    "product.update.claim_open": "Claim opened",
    "product.update.policy_change": "Policy change",
    "product.update.partnership": "Integration",
    "product.update.prototype": "Prototype published",
    "product.update.announcement": "Announcement",
    "product.update.milestone": "Product milestone",
  },
  ko: {
    "future.lead": "같은 제품에 흩어진 공식 게시물을 하나의 타임라인으로 묶어 현재 상태, 최신 변화, 원문 근거를 보여 줍니다.",
    "product.summaryLabel": "제품 동향 요약",
    "product.products": "개 제품",
    "product.updates": "회 상태 변화",
    "product.families": "개 제품군",
    "product.productsLabel": "제품 수",
    "product.updatesLabel": "상태 변화",
    "product.familiesLabel": "제품군",
    "product.method": "최신 공식 제품 이벤트만 현재 상태를 갱신합니다. 시장 결과, 이벤트, 설명 글은 관련 자료로만 유지됩니다.",
    "product.familyFilter": "제품군별 필터",
    "product.familyEyebrow": "PRODUCT FAMILY",
    "product.timeline": "제품 타임라인",
    "product.showTimeline": "전체 타임라인 보기",
    "product.lastVerified": "마지막 공식 근거",
    "product.related": "관련 공식 자료",
    "product.relatedLead": "제품을 언급하거나 보여 주지만 상태 변화 근거가 충분하지 않아 마일스톤으로 계산하지 않는 게시물입니다.",
    "product.candidateLead": "공식 신호는 있지만 제품 마일스톤을 만들기 위한 근거가 아직 부족합니다.",
    "product.noProducts": "정리할 수 있는 공식 제품 동향이 없습니다",
    "product.mode.experimental": "실험 프로토타입",
    "product.mode.candidate": "후보 제품",
    "product.unmappedTitle": "분류 대기 제품 근거",
    "product.unmappedLead": "네 가지 근거 조건을 모두 충족했지만 지속 가능한 제품 식별자가 없는 공식 게시물입니다. 가짜 제품을 만들지 않고 근거로 보관합니다.",
    "product.family.fair": "Fair & RIP",
    "product.family.gacha": "Infinite Gacha",
    "product.family.packs": "한정 팩",
    "product.family.sbt": "SBT 및 보상",
    "product.family.index": "Renaiss Index",
    "product.family.tech": "Tech Lab",
    "product.family.store": "스토어 교환",
    "product.family.platform": "플랫폼 기능 및 규칙",
    "product.family.vinci": "Vinci World",
    "product.status.candidate": "추가 근거 대기",
    "product.status.proposed": "제안 공개",
    "product.status.upcoming": "출시 예정",
    "product.status.live": "출시됨",
    "product.status.updated": "업데이트 중",
    "product.status.maintenance": "마지막 확인 상태: 점검 중",
    "product.status.adopted": "전체 적용",
    "product.status.sold_out": "매진",
    "product.status.claim_open": "수령 가능",
    "product.status.completed": "이번 단계 완료",
    "product.status.prototype": "프로토타입 공개",
    "product.status.expanding": "연동 구축 중",
    "product.status.restocked": "재입고 완료",
    "product.update.proposal": "제안",
    "product.update.implementation": "첫 제품 적용",
    "product.update.adoption": "전체 적용",
    "product.update.launch": "정식 출시",
    "product.update.content_update": "콘텐츠 또는 기능 업데이트",
    "product.update.maintenance": "점검",
    "product.update.restock": "재입고",
    "product.update.sold_out": "매진",
    "product.update.claim_open": "수령 개시",
    "product.update.policy_change": "규칙 변경",
    "product.update.partnership": "연동 구축",
    "product.update.prototype": "프로토타입 공개",
    "product.update.announcement": "출시 예고",
    "product.update.milestone": "제품 마일스톤",
  },
};

for (const lang of Object.keys(officialCategoryCopy) as Language[]) {
  Object.assign(copy[lang], officialCategoryCopy[lang], productDynamicsCopy[lang]);
}

export function text(lang: Language, key: string): string {
  return copy[lang][key] ?? copy["zh-Hant"][key] ?? key;
}
